# Generated by Django 3.2.12 on 2023-09-30 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('he_invited_me', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL, verbose_name='я пригласил')),
                ('i_invited', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred', to=settings.AUTH_USER_MODEL, verbose_name='меня пригласил')),
            ],
            options={
                'verbose_name_plural': 'реферальная ссылка',
            },
        ),
    ]
